// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDab2DOBCtcoE2OClRX_cnNb7foi4-gcQM',
    appId: '1:884836591001:web:7314d4a17d39f091685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    authDomain: 'safechat-7f27d.firebaseapp.com',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
    measurementId: 'G-WQTQ6SSDN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUgzmDMxZNlZ-nE9zqtJVjZ7FuhRS7Muw',
    appId: '1:884836591001:android:b11589968a636b33685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYtwudTQ1en5p59yQBGaKLRiWFBuT2gMk',
    appId: '1:884836591001:ios:8fab308dcc74ba9d685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
    androidClientId: '884836591001-bh2tcosas0e4e039iet4clf345uikfkr.apps.googleusercontent.com',
    iosClientId: '884836591001-i41ch4phb4574t0dod19kdhek60imq5p.apps.googleusercontent.com',
    iosBundleId: 'com.jasurbek.cyberchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYtwudTQ1en5p59yQBGaKLRiWFBuT2gMk',
    appId: '1:884836591001:ios:b4e00c274e34a22c685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
    androidClientId: '884836591001-bh2tcosas0e4e039iet4clf345uikfkr.apps.googleusercontent.com',
    iosClientId: '884836591001-8pnl6lhlrhv2qitbq34jr07pe4je0hha.apps.googleusercontent.com',
    iosBundleId: 'com.example.safechatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDab2DOBCtcoE2OClRX_cnNb7foi4-gcQM',
    appId: '1:884836591001:web:c1821f2ff6f16d5f685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    authDomain: 'safechat-7f27d.firebaseapp.com',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
    measurementId: 'G-ZRPE0WRSJ3',
  );

}