// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRkXSdVRxT8sqioUUfJsDGWE81xa1Ras',
    appId: '1:1028534793827:web:f2ffa1ba363d6f359f6a56',
    messagingSenderId: '1028534793827',
    projectId: 'cybercommunity',
    authDomain: 'cybercommunity.firebaseapp.com',
    storageBucket: 'cybercommunity.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRG__ntH99Y3vss1DIq47C2xgYg7ZnxwU',
    appId: '1:1028534793827:android:1914f87c4058d2f09f6a56',
    messagingSenderId: '1028534793827',
    projectId: 'cybercommunity',
    storageBucket: 'cybercommunity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeUgJ-enIovzXs4MM8yb8BCXLOrIb_zT0',
    appId: '1:1028534793827:ios:8df0ffd9799c34c79f6a56',
    messagingSenderId: '1028534793827',
    projectId: 'cybercommunity',
    storageBucket: 'cybercommunity.firebasestorage.app',
    iosBundleId: 'com.jasurbek.cyberchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeUgJ-enIovzXs4MM8yb8BCXLOrIb_zT0',
    appId: '1:1028534793827:ios:787a2373e64ecb709f6a56',
    messagingSenderId: '1028534793827',
    projectId: 'cybercommunity',
    storageBucket: 'cybercommunity.firebasestorage.app',
    iosBundleId: 'com.example.safechatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZRkXSdVRxT8sqioUUfJsDGWE81xa1Ras',
    appId: '1:1028534793827:web:d15a92cb4571b5f19f6a56',
    messagingSenderId: '1028534793827',
    projectId: 'cybercommunity',
    authDomain: 'cybercommunity.firebaseapp.com',
    storageBucket: 'cybercommunity.firebasestorage.app',
  );
}
